export const ROUTES = {
  AGENT_SKILLS_INDEX: "/.well-known/agent-skills/index.json",
  AGENT_SKILLS_SITE_SKILL: "/.well-known/agent-skills/site-skill.md",
  API_CATALOG: "/.well-known/api-catalog",
  API_STATUS: "/api/status",
  DOCS: "/docs",
  DOCS_BLOCK_EDITOR: "/docs/block-editor",
  DOCS_CHANGELOG: "/docs/changelog",
  DOCS_COMPONENTS: "/docs/components",
  DOCS_CUSTOMIZATION: "/docs/customization",
  DOCS_EDITOR: "/docs/editor",
  DOCS_GETTING_STARTED: "/docs/getting-started",
  DOCS_INSTALLATION: "/docs/installation",
  DOCS_MCP: "/docs/mcp",
  DOCS_OWNERSHIP: "/docs/ownership",
  DOCS_REGISTRY: "/docs/registry",
  DOCS_STATIC_RENDERER: "/docs/static-renderer",
  DOCS_STYLING: "/docs/styling",
  HOME: "/",
  LLMS: "/llms.txt",
  LLMS_FULL: "/llms-full.txt",
  LLMS_MD: "/llms.md",
  MANIFEST: "/manifest.webmanifest",
  OPENAPI: "/openapi.json",
  REGISTRY: "/r/registry.json",
  RSS: "/rss.xml",
  SPONSOR: "/sponsor",
} as const;
